### ISSUE TITLE
怎么添加域名后缀呢？

### ISSUE THREAD

**Issue by domainbf** [zmh-program/next-whois-ui#13]
很多域名后缀都不支持，
例如.cn
获取不到任何信息，
[TLDs Whois 解析器库源代码](https://github.com/zmh-program/next-whois-ui/blob/main/src/lib/whois/lib.ts)这里面我没看懂，怎么添加后缀

**Comment by zmh-program** [comment]
.cn怎么不支持啊

**Comment by zmh-program** [comment]
![whois-halo.cn (1).png](https://github.com/user-attachments/assets/eb6c4d08-732f-4fa2-bce6-546326c6d118)

**Comment by domainbf** [comment]
我没表达清楚，我的意思是条例后缀，
例如我的域名nic.bn，
他不支持，所以想让他可以查询到一些国别后缀，应该怎么做，

**Comment by zmh-program** [comment]
https://github.com/moneals/whois-raw

去这里提 issue，此项目 whois 查询依赖此项目

**Comment by domainbf** [comment]
算了，它这2年的库都没更新过了，估计也没戏。

期待加入新功能，
![IMG_9206](https://github.com/user-attachments/assets/d213ff50-9c53-403e-976e-de9ead5e517f)
https://www.nazhumi.com/api/v1

**Comment by zmh-program** [comment]
本开源项目不考虑任何外部api，含有推广性/不确定性

**Comment by zmh-program** [comment]
> 本开源项目不考虑任何外部api，含有推广性/不确定性

不过如果是比较著名的大厂是可以考虑的

**Comment by zmh-program** [comment]
![Screenshot_20240807_174032_com.microsoft.emmx_edit_471417795429072.jpg](https://github.com/user-attachments/assets/73c27aec-ebbd-4c9b-b572-23cd6ccca613)

我查的第一个，随便一个就会让人造成误解。
