### ISSUE TITLE
.edu result is wrong/unkown

### ISSUE THREAD

**Issue by dedecn** [zmh-program/next-whois-ui#16]
Domain: PITT.EDU
Registrar: Unknown
Creation Date: Unknown
Updated Date: 2024-10-19T00:00:00.000Z
Expiration Date: 2025-07-31T00:00:00.000Z

域名
pitt.edu
注册商
The EDUCAUSE Whois database is authoritative for the
更新时间
2024年09月11日
注册时间
1989年06月21日
过期时间
2025年07月31日

---------------------------------------------------------------------------
Domain: MONTEVALLO.EDU
Registrar: Unknown
Creation Date: Unknown
Updated Date: 2024-10-02T00:00:00.000Z
Expiration Date: 2025-07-31T00:00:00.000Z

域名
montevallo.edu
注册商
The EDUCAUSE Whois database is authoritative for the
更新时间
2024年01月18日
注册时间
1994年03月25日
过期时间
2025年07月31日

**Comment by zmh-program** [comment]
The odds are that this is a dependency issue. Please go to the project whois and check the dependencies to see if there is a solution: https://www.npmjs.com/package/whois-raw
