### ISSUE TITLE
对顶级域FUN的查询出现偏差

### ISSUE THREAD

**Issue by Ogannesson** [zmh-program/next-whois-ui#17]
当我在您提供的DEMO示例和我使用docker自行部署的实例中，对同一个顶级域FUN下的域名查询时出现了不同的结果，具体而言，**who.zmh.me**提供了正确的结果，而我创建的实例则报出了`Allow only queries : com,net,cc,tv`
who.zmh.me的结果：
![who.zmh.me的结果](https://github.com/user-attachments/assets/574a2017-b633-4515-9e7d-a60a7fbce58e)
我创建的实例的结果：
![我创建的实例的结果](https://github.com/user-attachments/assets/4282a9b6-4224-4563-be46-a278cf5182a6)

**Comment by zmh-program** [comment]
和 #16 一样，依赖库问题。现在没发现什么好的开源whois查询和解析module。

主要原因是维护几百个tld和parser太消耗精力了，所以一般成熟的whois tool只有大厂/调用大厂api的，比如godaddy, dnspod。

现在并没有找到一个无需填api key、无需付费的权威大厂whois解析api，可以直接无缝替代原先方案，因此保持现状。或者后续有时间，做个adapter兼容外部whois api吧

**Comment by Ogannesson** [comment]
主要是在你的demo中可以查到，但我自己部署的不行，显得很奇怪，这俩的上游不同吗？

**Comment by zmh-program** [comment]
我是用 vercel sin1 区域部署的。
![image](https://github.com/user-attachments/assets/45d249a9-6b0f-4076-80bb-8af9017830d6)
