### ISSUE TITLE
Lookup Failed

### ISSUE THREAD

**Issue by NoverNobida** [zmh-program/next-whois-ui#25]
First, let's say that my service is working properly:
![图片](https://github.com/user-attachments/assets/42ee6bd8-9a66-48b0-84e2-5bbf8a1f462e)

But for some domains, the query results are completely different on the self-hosted service and  who.zmh.me.
Examples:
1. 
self-hosted
![图片](https://github.com/user-attachments/assets/86003df2-500f-4e04-abe1-31a8fe31cbb1)

who.zmh.me
![图片](https://github.com/user-attachments/assets/c91f54b5-b2a0-4504-94cd-d0e94aae349a)

3. 
self-hosted
![图片](https://github.com/user-attachments/assets/56fb334d-3c3b-471e-a753-c98e815333e5)

who.zmh.me
![图片](https://github.com/user-attachments/assets/51a24e7b-895e-4d67-a095-674111b9289a)

**Comment by zmh-program** [comment]
duplicate #19
